---
- name: Update apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install NFS client packages
  apt:
    name: nfs-common
    state: present

- name: Create NFS mount directory
  file:
    path: "{{ nfs_mount_path }}"
    state: directory
    mode: '0755'

- name: Mount NFS share
  mount:
    path: "{{ nfs_mount_path }}"
    src: "{{ nfs_server_ip }}:{{ nfs_export_path }}"
    fstype: nfs
    opts: defaults
    state: mounted
